adds process id and kvfilter
sile/sloggers pull request #42
Opened 2021-06-06 14:15 UTC by przygienda

2021-06-13 01:08 UTC, sile commented
Could you tell me the state of this PR?
Is it ready for review?

2021-06-13 09:20 UTC, przygienda commented
should be. I merged with newest stuff, tests pass


On Sun, Jun 13, 2021 at 3:08 AM Takeru Ohta ***@***.***>
wrote:

> Could you tell me the state of this PR?
> Is it ready for review?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sile/sloggers/pull/42#issuecomment-860133683>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANDICYCTEWG4BDRJSQ2MTDTSQAIDANCNFSM46F7UCDQ>
> .
>

2021-06-13 09:36 UTC, sile requested changes
As the first review, I left a minor comment.
Besides, it seems that [a CI lint check](https://github.com/sile/sloggers/pull/42/checks?check_run_id=2757568271) has failed, so could you please fix that?

2021-06-13 09:36 UTC, sile commented on src/file.rs
> +    source_location: SourceLocation,
The above `common: BuilderCommon` field contains `source_location`, `level`, `channel_size`, and `kvfilterparameters`. So it seems that we don't need to re-introduce those fields here.

2021-06-13 09:38 UTC, sile commented
I'll take a more detailed look at this PR when I have time (I'll busy this week, so that may become next week or later).

2021-06-30 01:39 UTC, sile commented
(I'm waiting for the CI failure to be resolved to restart PR review)

2024-01-25 00:11 UTC, sile commented
Let me close this PR as there have been no activities for a long time.

2024-01-25 00:11 UTC, closed without merging